- set_fact:
    current_domain_folder: "{{ acme_ssl_base_folder }}/{{ current_domain|mandatory }}"

- name: "Setup SSL domains folders for {{ current_domain }}"
  file:
    path: "{{ current_domain_folder }}"
    state: directory
    owner: "{{ acme_user }}"
    group: www-data
    mode: 0750

- name: Ensure that a domain private key exists
  shell: "openssl genrsa 4096 > {{ current_domain_folder }}/domain.key"
  args:
    creates: "{{ current_domain_folder }}/domain.key"
  when: acme_copy_from_hostname == ''

- include: copy_from_hostname.yml
  when: acme_copy_from_hostname != ''

- name: setup domain private key perms
  file:
    path: "{{ current_domain_folder }}/domain.key"
    owner: "{{ acme_user }}"
    group: www-data
    mode: 0640
   
- include: sign.yml
  become: yes
  become_user: "{{ acme_user }}"

- include: acme.yml
  become: yes
  become_user: "{{ acme_user }}"

- name: Generate nginx snippet for domain-specific SSL conf
  template: src=domain_ssl.conf dest=/etc/nginx/snippets/{{ current_domain }}.ssl.conf

